### ISSUE TITLE
There's a mistake in the code which makes the links from "URL" section not transfer when there's any text in the post's body.

### ISSUE THREAD

**Issue by M4rtineski** [fmhy/maliciouscompliance#3]
Problem explained in the title.

Examples of the not complete posts:
https://lemmy.fmhy.net/c/games
https://lemmy.fmhy.net/c/singularityai

When checking the trasfered posts you will notice that any posts that have links don't have anything in their bodies and posts that have text in bodies are missing their links (not every post had a link but majority of them did).

**Comment by taskylizard** [comment]
I assumed posts can only contain either of them like other link aggregators, so this was intended but will fix.

**Comment by M4rtineski** [comment]
A specific example of post not being properly migrated: 

Post on old instance: https://lemmy.world/post/1806562

Migrated post: https://lemmy.fmhy.net/post/368491
